// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://evpeimuwyxuvttmzaewj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV2cGVpbXV3eXh1dnR0bXphZXdqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5MjcxNTQsImV4cCI6MjA2MDUwMzE1NH0.nTPvdM0j-siXiPobkvOiuo-60JHrlfxUGm8hu0YfWaA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);